package db

import (
	"time"

	"context"
	"github.com/Kungfucoding23/Golang-Final-Proyect/models"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// InsertoRegistro es la parada final con la BD para insertar los datos del ususario
func InsertoRegistro(u models.Usuario) (string, bool, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	// Database devuelve un identificador para una base de datos con el nombre dado configurado con las DatabaseOptions dadas.
	db := MongoCN.Database("microblogging")
	// Collection obtiene un identificador para una colección con el nombre dado configurado con las CollectionOptions dadas.
	col := db.Collection("usuarios")
	u.Password, _ = EncriptarPassword(u.Password)
	// InsertOne inserta un solo documento en la coleccion
	// para insertar varios usar InsertMany()
	result, err := col.InsertOne(ctx, u)
	if err != nil {
		return "", false, err
	}
	// 	// The _id of the inserted document. A value generated by the driver will be of type primitive.ObjectID.
	ObjID, _ := result.InsertedID.(primitive.ObjectID)
	// if ObjID, _ := result.InsertedID(primitive.ObjectID); ok {
	// 	return u.bson(http.StatusCreated, map[string]interface{}{
	// 		"id": ObjID.String(),
	// 	})
	// }
	return ObjID.String(), true, nil
}
